services:
  postgres:
    image: postgres:17
    container_name: sole-reax-postgres
    environment:
      POSTGRES_DB: sole_reax
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sole-reax-db:/var/lib/postgresql/data

volumes:
  sole-reax-db:
