spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory?currentSchema=inventory_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: inventory_test

  flyway:
    enabled: false

app:
  jwt:
    secret: TEST_SECRET_CHANGE_ME_TO_LONG_RANDOM_SECRET_123456
    expiration-minutes: 60
