/**
 * Device Detection Cache Utility
 *
 * Caches device type, orientation, and feature detection results
 * to avoid recalculation on every render.
 *
 * Cache key is based on viewport dimensions + user agent + DPI
 * Cache is invalidated when viewport size changes significantly
 */

// In-memory cache for device detection results
const cache = new Map();

// Maximum cache entries to prevent memory leaks
const MAX_CACHE_SIZE = 50;

/**
 * Generate a cache key from viewport dimensions and device properties
 * @param {number} width - Viewport width
 * @param {number} height - Viewport height
 * @param {string} userAgent - Navigator user agent string
 * @param {number} dpi - Device pixel ratio
 * @returns {string} Cache key
 */
export function generateCacheKey(width, height, userAgent, dpi) {
  // Round to nearest 10px to increase cache hit rate for minor resize events
  const roundedWidth = Math.round(width / 10) * 10;
  const roundedHeight = Math.round(height / 10) * 10;

  // Create deterministic key from normalized values
  return `device_${roundedWidth}x${roundedHeight}_${dpi}_${userAgent.substring(0, 50)}`;
}

/**
 * Get cached device detection result
 * @param {string} cacheKey - Cache key generated by generateCacheKey()
 * @returns {object|null} Cached device detection result or null if not cached
 */
export function getCachedDeviceProfile(cacheKey) {
  return cache.get(cacheKey) || null;
}

/**
 * Store device detection result in cache
 * @param {string} cacheKey - Cache key
 * @param {object} deviceProfile - Device profile object to cache
 */
export function setCachedDeviceProfile(cacheKey, deviceProfile) {
  // Prevent cache from growing too large
  if (cache.size >= MAX_CACHE_SIZE) {
    // Remove oldest entry (simple FIFO strategy)
    const firstKey = cache.keys().next().value;
    cache.delete(firstKey);
  }

  cache.set(cacheKey, deviceProfile);
}

/**
 * Clear all cached device profiles
 * Useful for testing or force-refresh scenarios
 */
export function clearDeviceCache() {
  cache.clear();
}

/**
 * Get cache statistics for debugging
 * @returns {object} Cache stats
 */
export function getCacheStats() {
  return {
    size: cache.size,
    maxSize: MAX_CACHE_SIZE,
    keys: Array.from(cache.keys()),
    usage: `${cache.size}/${MAX_CACHE_SIZE}`,
  };
}

export default {
  generateCacheKey,
  getCachedDeviceProfile,
  setCachedDeviceProfile,
  clearDeviceCache,
  getCacheStats,
};

