CREATE TABLE product_colorway_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    colorway VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    department VARCHAR(30),
    category VARCHAR(30),
    product_type VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_colorway_detail UNIQUE (product_id, colorway)
);

INSERT INTO product_colorway_details (product_id, colorway, description, department, category, product_type)
SELECT DISTINCT
    product_id,
    colorway,
    description,
    department,
    category,
    product_type
FROM (
    SELECT
        p.id AS product_id,
        COALESCE(NULLIF(TRIM(ps.colorway), ''), 'DEFAULT') AS colorway,
        p.description,
        p.department,
        p.category,
        p.product_type
    FROM products p
    JOIN product_stocks ps ON ps.product_id = p.id

    UNION

    SELECT
        p.id AS product_id,
        COALESCE(NULLIF(TRIM(pci.colorway), ''), 'DEFAULT') AS colorway,
        p.description,
        p.department,
        p.category,
        p.product_type
    FROM products p
    JOIN product_colorway_images pci ON pci.product_id = p.id

    UNION

    SELECT
        p.id AS product_id,
        COALESCE(NULLIF(TRIM(p.main_color), ''), 'DEFAULT') AS colorway,
        p.description,
        p.department,
        p.category,
        p.product_type
    FROM products p
) seeded;

