-- Customer Profiles Table (for guests with just username, no auth required)
CREATE TABLE customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    points_balance INT NOT NULL DEFAULT 0,
    total_points_earned INT NOT NULL DEFAULT 0,
    purchases_count INT NOT NULL DEFAULT 0,
    reviews_count INT NOT NULL DEFAULT 0,
    referrals_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at TIMESTAMP
);

CREATE INDEX idx_customer_profiles_username ON customer_profiles(username);

-- Badge Definitions (predefined badges in the system)
CREATE TABLE badge_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    icon_emoji VARCHAR(10),
    condition_type VARCHAR(50) NOT NULL, -- PURCHASES, REVIEWS, REFERRALS, EARLY_BIRD, COLOR_COLLECTOR
    condition_threshold INT NOT NULL DEFAULT 0,
    points_reward INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed default badges
INSERT INTO badge_definitions (code, name, description, icon_emoji, condition_type, condition_threshold, points_reward, active) VALUES
('SNEAKERHEAD', 'Sneakerhead', 'Bought 5+ items', '🥾', 'PURCHASES', 5, 50, TRUE),
('COLLECTOR', 'Collector', 'Bought all colors of one shoe', '👟', 'COLOR_COLLECTOR', 1, 30, TRUE),
('FIVE_STAR_REVIEWER', '5-Star Reviewer', 'Left 5-star reviews', '⭐', 'REVIEWS', 1, 20, TRUE),
('EARLY_BIRD', 'Early Bird', 'Made purchase on first day', '🎯', 'EARLY_BIRD', 1, 15, TRUE),
('GIFT_GIVER', 'Gift Giver', 'Referred 3+ friends', '💝', 'REFERRALS', 3, 75, TRUE);

-- Customer Badges (earned badges for each customer)
CREATE TABLE customer_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer_profiles(id) ON DELETE CASCADE,
    badge_id BIGINT NOT NULL REFERENCES badge_definitions(id),
    earned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_customer_badge UNIQUE (customer_id, badge_id)
);

CREATE INDEX idx_customer_badges_customer ON customer_badges(customer_id);

-- Daily Activities (for daily spin wheel and activities)
CREATE TABLE daily_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer_profiles(id) ON DELETE CASCADE,
    activity_type VARCHAR(50) NOT NULL, -- SPIN_WHEEL, PURCHASE, REVIEW, REFERRAL
    points_earned INT NOT NULL,
    activity_date DATE NOT NULL,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_daily_activities_customer ON daily_activities(customer_id);
CREATE INDEX idx_daily_activities_date ON daily_activities(activity_date);

-- Points Redemptions (track when customers redeem points)
CREATE TABLE points_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer_profiles(id) ON DELETE CASCADE,
    points_amount INT NOT NULL,
    redemption_type VARCHAR(50) NOT NULL, -- DISCOUNT_CODE, FREE_SHIPPING
    reference_id VARCHAR(120),
    redeemed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_points_redemptions_customer ON points_redemptions(customer_id);

-- Link orders to customer profile (add foreign key reference)
ALTER TABLE customer_orders ADD COLUMN customer_profile_id BIGINT REFERENCES customer_profiles(id);
CREATE INDEX idx_customer_orders_profile ON customer_orders(customer_profile_id);

